### ISSUE TITLE
Evaluate if HR is a good secondary target for robust learning. 

### ISSUE THREAD

**Issue by gianlucatruda** [gianlucatruda/Spo2_evaluation#4]
SpO2 seems too tightly clustered for reasonable learning within the acceptable error bounds. What if we validate our models on HR instead?

**Comment by gianlucatruda** [comment]
Clearly there is much more spread on HR compared to SpO2. This is on the superset of Nemcova, Community, and Clinical data to date.


![image](https://user-images.githubusercontent.com/1952799/81178144-0cc90600-8fa8-11ea-95fc-dd723f411eab.png)

**Comment by gianlucatruda** [comment]
Okay, so I did the following preparation:
* combined Nemcova, Clinical, and Community data -> 67 samples
* augmented the samples (by chopping each into a block of 200 frames) -> 158 samples
* generated PPG features using both Lamonaca and my own methodology for means of each colour channel -> 16 features

Then, I used tsfresh to perform feature engineering for each (augmented) sample. I repeated this using `spo2` as the target and using `hr` as the target.

**Result**: Neither `spo2` nor `hr` return any significant features when using tsfresh's built-in F-test. Sklearn's KBest function gives very different features for `spo2` and `hr`

Here follow the details:

## SpO2 target
```
In [251]: all_features = engineer_features(X, Y, target='spo2', select=False); features = engineer_features(X, Y, 
     ...: target='spo2', select=True) 

In [252]: features.shape, all_features.shape                                                                      
Out[252]: ((158, 1), (158, 9829))

In [254]: k_best_features = select_best_features(all_features, n_features=30, target='spo2')
In [255]: k_best_features.shape                                                                                   
Out[255]: (158, 31)

In [256]: k_best_features.columns                                                                                 
Out[256]: 
Index(['mean_green__index_mass_quantile__q_0.7',
       'mean_green__index_mass_quantile__q_0.8',
       'mean_green__index_mass_quantile__q_0.9',
       'std_blue__agg_linear_trend__f_agg_"var"__chunk_len_10__attr_"stderr"',
       'std_blue__change_quantiles__f_agg_"mean"__isabs_True__qh_0.8__ql_0.6',
       'std_blue__change_quantiles__f_agg_"var"__isabs_False__qh_0.8__ql_0.6',
       'std_blue__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.6',
       'std_blue__minimum',
       'std_green__change_quantiles__f_agg_"mean"__isabs_True__qh_0.8__ql_0.6',
       'std_green__change_quantiles__f_agg_"var"__isabs_False__qh_0.8__ql_0.6',
       'std_green__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.6',
       'std_green__fft_aggregated__aggtype_"centroid"',
       'std_green__index_mass_quantile__q_0.7',
       'std_green__index_mass_quantile__q_0.8',
       'std_green__index_mass_quantile__q_0.9',
       'std_green__number_crossing_m__m_1', 'std_green__variance',
       'std_red__agg_linear_trend__f_agg_"mean"__chunk_len_10__attr_"stderr"',
       'std_red__agg_linear_trend__f_agg_"mean"__chunk_len_50__attr_"stderr"',
       'std_red__agg_linear_trend__f_agg_"var"__chunk_len_5__attr_"stderr"',
       'std_red__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.0',
       'std_red__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.6',
       'std_red__fft_coefficient__coeff_13__attr_"abs"',
       'std_red__fft_coefficient__coeff_1__attr_"abs"',
       'std_red__standard_deviation', 'std_red__variance',
       'tx_green_scaled__fft_coefficient__coeff_13__attr_"abs"',
       'tx_red__change_quantiles__f_agg_"mean"__isabs_False__qh_0.6__ql_0.4',
       'tx_red_scaled__fft_coefficient__coeff_13__attr_"abs"',
       'tx_red_scaled__fft_coefficient__coeff_26__attr_"abs"', 'spo2'],
      dtype='object')
```

## HR target

```
In [257]: all_features = engineer_features(X, Y, target='hr', select=False); features = engineer_features(X, Y, ta
     ...: rget='hr', select=True); k_best_features = select_best_features(all_features, n_features=30, target='hr'
     ...: )   

In [258]: features.shape, all_features.shape, k_best_features.shape                                               
Out[258]: ((158, 1), (158, 9829), (158, 31))

In [259]: k_best_features.columns                                                                                 
Out[259]: 
Index(['mean_red__friedrich_coefficients__m_3__r_30__coeff_0',
       'mean_red__friedrich_coefficients__m_3__r_30__coeff_1',
       'mean_red__friedrich_coefficients__m_3__r_30__coeff_2',
       'mean_red__friedrich_coefficients__m_3__r_30__coeff_3',
       'mean_red__has_duplicate_min',
       'original_sample_id__fft_coefficient__coeff_14__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_19__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_24__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_29__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_34__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_39__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_44__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_49__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_4__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_54__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_59__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_64__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_69__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_74__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_79__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_81__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_84__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_86__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_89__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_91__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_94__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_96__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_99__attr_"angle"',
       'original_sample_id__fft_coefficient__coeff_9__attr_"angle"',
       'std_green__friedrich_coefficients__m_3__r_30__coeff_0', 'hr'],
      dtype='object')
```

**Comment by gianlucatruda** [comment]
I decided to go ahead and do some actual regression on the above feature sets for both `hr` and `spo2`:

I did a grid search over both targets, 3 different models, and 7 K-values (for KBest feature selector) from 6-80, all with 5-fold CV:

```python
from sklearn.metrics import mean_squared_error as mse
from sklearn.linear_model import LassoLars
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from tqdm import tqdm
from sklearn.model_selection import KFold
import json
from pandas.io.json import json_normalize

targets = ['spo2', 'hr']
models = [XGBRegressor, LassoLars, MLPRegressor]
model_names = ['xgboost', 'lasso', 'mlp']
K_vals = [6, 10, 15, 20, 30, 50, 80]

results = {'target': [], 'model': [], 'k': [], 'mse': []}

for target in targets:
    print(f"Evaluating {target}...")
    for K in tqdm(K_vals):
        _X = all_features.drop(targets, axis=1).values
        _y = all_features[target].values
        kbest = SelectKBest(f_classif, k=K).fit(_X, _y)
        _X = _X[:, kbest.get_support()]
        kf = KFold(n_splits=5)
        for train_index, test_index in kf.split(_X):
            X_train, X_test = _X[train_index], _X[test_index]
            y_train, y_test = _y[train_index], _y[test_index]
            for model, mname in zip(models, model_names):
                mod = model().fit(X_train, y_train)
                score = mse(y_test, mod.predict(X_test))
                for key, value in {'target': target, 'model': mname, 'mse': score, 'k': K}.items():
                    results[key].append(value)

pd.DataFrame.from_dict(results)
```

```
In [346]: results.groupby(['target', 'model', 'k']).mean()
Out[356]: 
   target    model   k                mse
0      hr    lasso   6            168.319
1      hr    lasso  10            168.319
2      hr    lasso  15            168.319
3      hr    lasso  20            168.319
4      hr    lasso  30            168.319
5      hr    lasso  50            168.319
6      hr    lasso  80            168.319
7      hr      mlp   6   412307955173.137
8      hr      mlp  10   411422899139.065
9      hr      mlp  15 30148866297893.977
10     hr      mlp  20  6794489122569.918
11     hr      mlp  30   282823195167.702
12     hr      mlp  50   614836078512.462
13     hr      mlp  80 31797942757376.238
14     hr  xgboost   6            254.428
15     hr  xgboost  10            223.821
16     hr  xgboost  15            223.821
17     hr  xgboost  20            223.821
18     hr  xgboost  30            223.821
19     hr  xgboost  50            150.901
20     hr  xgboost  80            155.151
21   spo2    lasso   6              5.543
22   spo2    lasso  10              5.543
23   spo2    lasso  15              5.543
24   spo2    lasso  20              5.543
25   spo2    lasso  30              5.543
26   spo2    lasso  50              5.543
27   spo2    lasso  80              5.543
28   spo2      mlp   6           3532.801
29   spo2      mlp  10           6658.316
30   spo2      mlp  15           5751.636
31   spo2      mlp  20           4157.674
32   spo2      mlp  30           3256.911
33   spo2      mlp  50           6114.408
34   spo2      mlp  80           9457.771
35   spo2  xgboost   6              6.205
36   spo2  xgboost  10              5.969
37   spo2  xgboost  15              4.616
38   spo2  xgboost  20              8.607
39   spo2  xgboost  30              8.049
40   spo2  xgboost  50              7.944
41   spo2  xgboost  80              7.789

```

**Comment by gianlucatruda** [comment]
Surprisingly, the features actually seem to help the ensemble predict HR even as they approach `samples / 2`

![image](https://user-images.githubusercontent.com/1952799/81199820-760a4280-8fc3-11ea-9dbd-ce0a7f89ab29.png)

**Comment by gianlucatruda** [comment]
# TODO

- [ ] Repeat the above analysis for different augmentations of the data (100 frames, 300 frames, rolling window, etc.)
- [ ] Inspect the augmented samples to see how the PPG curves look to the eye.
- [x] Improve the preprocessing that generates the PPGs so the resulting curves look better.

**Comment by gianlucatruda** [comment]
Okay, I’ve implemented a function that does windowed augmentation. 

Basically, it trims 20 frames from each end, then moves along each sample in steps of 10 frames and creates new samples of 200 frames long. All of those values are configurable, of course.

Then I ran the same evaluation code from above.

```
Out[156]: 
   target    model   k           mse
0      hr    lasso   6       173.351
1      hr    lasso  10       173.351
2      hr    lasso  15       173.351
3      hr    lasso  20       173.351
4      hr    lasso  30       173.351
5      hr    lasso  50       173.351
6      hr    lasso  80       173.351
7      hr      mlp   6  36376774.186
8      hr      mlp  10 376781216.432
9      hr      mlp  15  89041135.687
10     hr      mlp  20  32416546.172
11     hr      mlp  30  16740762.391
12     hr      mlp  50 113770558.119
13     hr      mlp  80 267015412.572
14     hr  xgboost   6       179.243
15     hr  xgboost  10       165.679
16     hr  xgboost  15       152.105
17     hr  xgboost  20       146.281
18     hr  xgboost  30       172.279
19     hr  xgboost  50       175.192
20     hr  xgboost  80       165.218
21   spo2    lasso   6         5.671
22   spo2    lasso  10         5.671
23   spo2    lasso  15         5.671
24   spo2    lasso  20         5.671
25   spo2    lasso  30         5.671
26   spo2    lasso  50         5.671
27   spo2    lasso  80         5.671
28   spo2      mlp   6       145.415
29   spo2      mlp  10       928.593
30   spo2      mlp  15      2265.844
31   spo2      mlp  20      6617.876
32   spo2      mlp  30      1843.179
33   spo2      mlp  50      1740.086
34   spo2      mlp  80      1740.693
35   spo2  xgboost   6         7.041
36   spo2  xgboost  10         8.086
37   spo2  xgboost  15        10.186
38   spo2  xgboost  20        10.143
39   spo2  xgboost  30         9.850
40   spo2  xgboost  50         9.265
41   spo2  xgboost  80        10.615
```

**Comment by gianlucatruda** [comment]
I ran it again on the augmented data from above, but instead of 5-fold CV I used 10-fold CV. Instead of an MLP model (which always failed to converge), I used the default linear regression model. I also tested more values for K in the feature selector.

```
In [184]: df                                                                                                        
Out[184]: 
   target    model   k       mse
0      hr    lasso   2   176.344
1      hr    lasso   3   176.344
2      hr    lasso   5   176.344
3      hr    lasso  10   176.344
4      hr    lasso  15   176.344
5      hr    lasso  20   176.344
6      hr    lasso  30   176.344
7      hr    lasso  40   176.344
8      hr    lasso  50   176.344
9      hr    lasso  60   176.344
10     hr    lasso  70   176.344
11     hr    lasso  80   176.344
12     hr       lr   2   227.348
13     hr       lr   3   227.416
14     hr       lr   5   221.833
15     hr       lr  10 16534.386
16     hr       lr  15  6558.379
17     hr       lr  20  6593.948
18     hr       lr  30 10363.104
19     hr       lr  40  8703.425
20     hr       lr  50  9207.794
21     hr       lr  60  4919.543
22     hr       lr  70  3565.501
23     hr       lr  80  3565.501
24     hr  xgboost   2   182.995
25     hr  xgboost   3   182.927
26     hr  xgboost   5   136.706
27     hr  xgboost  10   122.131
28     hr  xgboost  15   132.115
29     hr  xgboost  20   127.268
30     hr  xgboost  30   155.816
31     hr  xgboost  40   171.225
32     hr  xgboost  50   168.176
33     hr  xgboost  60   155.894
34     hr  xgboost  70   148.452
35     hr  xgboost  80   148.452
36   spo2    lasso   2     5.687
37   spo2    lasso   3     5.687
38   spo2    lasso   5     5.687
39   spo2    lasso  10     5.687
40   spo2    lasso  15     5.687
41   spo2    lasso  20     5.687
42   spo2    lasso  30     5.687
43   spo2    lasso  40     5.687
44   spo2    lasso  50     5.687
45   spo2    lasso  60     5.687
46   spo2    lasso  70     5.687
47   spo2    lasso  80     5.687
48   spo2       lr   2     4.444
49   spo2       lr   3     4.616
50   spo2       lr   5     4.689
51   spo2       lr  10    35.166
52   spo2       lr  15    33.474
53   spo2       lr  20    20.502
54   spo2       lr  30    74.640
55   spo2       lr  40    87.413
56   spo2       lr  50    76.905
57   spo2       lr  60   220.018
58   spo2       lr  70  1203.164
59   spo2       lr  80  2382.133
60   spo2  xgboost   2     5.859
61   spo2  xgboost   3     5.879
62   spo2  xgboost   5     4.607
63   spo2  xgboost  10     6.400
64   spo2  xgboost  15     5.817
65   spo2  xgboost  20     6.173
66   spo2  xgboost  30     6.166
67   spo2  xgboost  40     6.013
68   spo2  xgboost  50     6.149
69   spo2  xgboost  60     6.590
70   spo2  xgboost  70     6.283
71   spo2  xgboost  80     6.319
```

**Comment by gianlucatruda** [comment]
For reference, a model that just guessed the mean of the dataset for every sample would score the following MSE for each target:

```
In [191]: mse(all_features.spo2, [all_features.spo2.mean() for i in range(2322)])                                   
Out[191]: 5.481907507932587

In [192]: mse(all_features.hr, [all_features.hr.mean() for i in range(2322)])                                       
Out[192]: 170.18685089853187
```

**Comment by gianlucatruda** [comment]
We might want to reference this methodology or some of the results in the paper, but I think we've got all the answers we need from here, so I'm gonna close this.

**Comment by gianlucatruda** [comment]
Update: We can use Minimal or Efficient subsets of tsfresh feature engineering. Minimal seems to be faster (and actually more performant) when applying to `std_`, `tx_`, `skewness`, and `kldiv`, and doing subsequent feature selection with SelectKBest.

```
In [23]: minim.sort_values('mse')                                                                                      
Out[23]: 
     aug_window target    model   k      mse
60          120   spo2  xgboost  30    0.272
285         160   spo2  xgboost  40    0.331
75          120   spo2  xgboost  40    0.369
225         160   spo2  xgboost  10    0.373
465         200   spo2  xgboost  20    0.388
..          ...    ...      ...  ..      ...
593         200     hr       lr  30 2932.923
743         240     hr       lr   5 3237.446
563         200     hr       lr  15 3902.910
773         240     hr       lr  15 5142.668
533         200     hr       lr   5 5381.260

[840 rows x 5 columns]

In [24]: eff.sort_values('mse')                                                                                        
Out[24]: 
     aug_window target    model   k           mse
300         160   spo2  xgboost  30         0.460
330         160   spo2  xgboost  50         0.539
90          120   spo2  xgboost  50         0.553
75          120   spo2  xgboost  40         0.559
105         120   spo2  xgboost  60         0.687
..          ...    ...      ...  ..           ...
698         200     hr       lr  50 137063928.523
908         240     hr       lr  30 517585549.294
923         240     hr       lr  40 517585549.294
938         240     hr       lr  50 517585549.294
953         240     hr       lr  60 710365246.530

[960 rows x 5 columns]
```
